import { IPlanoCurricular, NewPlanoCurricular } from './plano-curricular.model';

export const sampleWithRequiredData: IPlanoCurricular = {
  id: 26888,
  descricao: 'optimal',
  formulaClassificacaoFinal: 'auxiliary transmitter',
  numeroDisciplinaAprova: 75021,
  numeroDisciplinaReprova: 91172,
  numeroDisciplinaRecurso: 12003,
  numeroDisciplinaExame: 69376,
  numeroDisciplinaExameEspecial: 50185,
  numeroFaltaReprova: 87320,
  siglaProva1: 'Bola',
  siglaProva2: 'program',
  siglaProva3: 'Tanzânia JSON',
  siglaMedia1: 'deposit Inteligente Versatile',
  siglaMedia2: 'alarm Intuitive Dynamic',
  siglaMedia3: 'Colômbia niches Tanzânia',
  formulaMedia: 'backing Account Communications',
  formulaDispensa: 'Buckinghamshire intermediate',
  formulaExame: 'impactful',
  formulaRecurso: 'primary',
  formulaExameEspecial: 'amarelo eco-centric',
};

export const sampleWithPartialData: IPlanoCurricular = {
  id: 74989,
  descricao: 'transform Cambridgeshire',
  formulaClassificacaoFinal: 'transitional compress Avon',
  numeroDisciplinaAprova: 73569,
  numeroDisciplinaReprova: 34270,
  numeroDisciplinaRecurso: 65557,
  numeroDisciplinaExame: 78546,
  numeroDisciplinaExameEspecial: 62798,
  numeroFaltaReprova: 43721,
  pesoMedia2: 53,
  pesoMedia3: 97,
  pesoExame: 98,
  pesoExameEspecial: 69,
  pesoNotaCoselho: 95,
  siglaProva1: 'Rica Dinar',
  siglaProva2: 'Checking Jóias',
  siglaProva3: 'THX',
  siglaMedia1: 'experiences Universal zero',
  siglaMedia2: 'integrate Dollar',
  siglaMedia3: 'Genérico',
  formulaMedia: 'cinzento Portugal Down-sized',
  formulaDispensa: 'Dirham',
  formulaExame: 'Bedfordshire invoice best-of-breed',
  formulaRecurso: 'JBOD open-source',
  formulaExameEspecial: 'Carolina Phased',
};

export const sampleWithFullData: IPlanoCurricular = {
  id: 518,
  descricao: 'actuating programming Cambridgeshire',
  formulaClassificacaoFinal: 'European',
  numeroDisciplinaAprova: 81050,
  numeroDisciplinaReprova: 99688,
  numeroDisciplinaRecurso: 94601,
  numeroDisciplinaExame: 61392,
  numeroDisciplinaExameEspecial: 10140,
  numeroFaltaReprova: 907,
  pesoMedia1: 73,
  pesoMedia2: 72,
  pesoMedia3: 58,
  pesoRecurso: 20,
  pesoExame: 20,
  pesoExameEspecial: 88,
  pesoNotaCoselho: 46,
  siglaProva1: 'Automóveis Principal deposit',
  siglaProva2: 'cross-platform Missouri Francesa',
  siglaProva3: 'leading-edge structure',
  siglaMedia1: 'Genérico',
  siglaMedia2: 'infomediaries overriding',
  siglaMedia3: 'bypassing loyalty',
  formulaMedia: 'Associate Engineer',
  formulaDispensa: 'invoice',
  formulaExame: 'bypassing',
  formulaRecurso: 'Designer Credit',
  formulaExameEspecial: 'bluetooth capacitor',
};

export const sampleWithNewData: NewPlanoCurricular = {
  descricao: 'ameixa Kentucky alarm',
  formulaClassificacaoFinal: 'Fantástico installation',
  numeroDisciplinaAprova: 89922,
  numeroDisciplinaReprova: 73285,
  numeroDisciplinaRecurso: 97688,
  numeroDisciplinaExame: 53465,
  numeroDisciplinaExameEspecial: 42100,
  numeroFaltaReprova: 53128,
  siglaProva1: 'Checking Mandatory SQL',
  siglaProva2: 'New open-source',
  siglaProva3: 'XSS Track Administrator',
  siglaMedia1: 'Malaysian killer',
  siglaMedia2: 'Saboroso',
  siglaMedia3: 'efficient',
  formulaMedia: 'Missouri',
  formulaDispensa: 'compressing New',
  formulaExame: 'Pequeno Facilitator',
  formulaRecurso: 'Loan',
  formulaExameEspecial: 'Legacy',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
